export const FETCH_MODULGRUPS = "FETCH_MODULGRUPS";
export const FETCH_MODULGRUPS_PENDING = "FETCH_MODULGRUPS_PENDING";
export const FETCH_MODULGRUPS_SUCCESS = "FETCH_MODULGRUPS_SUCCESS";
export const FETCH_MODULGRUPS_FAILURE = "FETCH_MODULGRUPS_FAILURE";

export const DELETE_MODULGRUP = "DELETE_MODULGRUP";
export const DELETE_MODULGRUP_PENDING = "DELETE_MODULGRUP_PENDING";
export const DELETE_MODULGRUP_SUCCESS = "DELETE_MODULGRUP_SUCCESS";
export const DELETE_MODULGRUP_FAILURE = "DELETE_MODULGRUP_FAILURE";

export const CREATE_MODULGRUP = "CREATE_MODULGRUP";
export const CREATE_MODULGRUP_PENDING = "CREATE_MODULGRUP_PENDING";
export const CREATE_MODULGRUP_SUCCESS = "CREATE_MODULGRUP_SUCCESS";
export const CREATE_MODULGRUP_FAILURE = "CREATE_MODULGRUP_FAILURE";

export const UPDATE_MODULGRUP = "UPDATE_MODULGRUP";
export const UPDATE_MODULGRUP_PENDING = "UPDATE_MODULGRUP_PENDING";
export const UPDATE_MODULGRUP_SUCCESS = "UPDATE_MODULGRUP_SUCCESS";
export const UPDATE_MODULGRUP_FAILURE = "UPDATE_MODULGRUP_FAILURE";

export default {
  FETCH_MODULGRUPS,
  FETCH_MODULGRUPS_PENDING,
  FETCH_MODULGRUPS_SUCCESS,
  FETCH_MODULGRUPS_FAILURE,
  DELETE_MODULGRUP,
  DELETE_MODULGRUP_PENDING,
  DELETE_MODULGRUP_SUCCESS,
  DELETE_MODULGRUP_FAILURE,
  CREATE_MODULGRUP,
  CREATE_MODULGRUP_PENDING,
  CREATE_MODULGRUP_SUCCESS,
  CREATE_MODULGRUP_FAILURE,
  UPDATE_MODULGRUP,
  UPDATE_MODULGRUP_PENDING,
  UPDATE_MODULGRUP_SUCCESS,
  UPDATE_MODULGRUP_FAILURE,
};
